image:
  name: circleci/ruby:2.6-node-browsers

stages:
  - test
  - deploy

test:
  stage: test
  before_script:  
    - npm install
    - bundle install --path vendor/bundler --jobs=4 --retry=3
  script:
    - ./generate.js source/v2/openapi.yaml source/reference.html.md.erb
    - bundle exec rake build API_SPEC=source/v2/openapi.yaml
  artifacts:
    paths:
      - build
  cache:
    key: ${CI_JOB_NAME}-v2
    paths:
      - vendor/bundler
      - node_modules/

deploy_dev:
  stage: deploy
  script:
    - curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
    - sudo dpkg -i cf-cli_amd64.deb
    - cf -v
    - CF_SPACE=development CF_APP=tariff-api-dev ./bin/deploy
  only:
    - master

deploy_production:
  stage: deploy
  script:
    - curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
    - sudo dpkg -i cf-cli_amd64.deb
    - cf -v
    - CF_SPACE=production CF_APP=tariff-api-production ./bin/deploy
  when: manual
  only:
  - production
